version: "3"
services:
  www:
    build: .
    environment:
        XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
    ports:
      - "4000:80"
    volumes: 
      - ".:/var/www/html/"
    networks:
      - default